import Head from "next/head";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import NavBar from "../components/Navbar";
import Resume from "../components/Resume";
import Works from "../components/Works";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.png' />
      </Head>
      <NavBar />
      <main>
        <Hero />
        <Works />
        <Resume />
      </main>
      <Footer />
    </div>
  );
}
